### ISSUE TITLE
Build Failure with Anchor Dependencies Below Version 0.30.1

### ISSUE THREAD

**Issue by sirkuredda** [orca-so/whirlpool-cpi#4]
All the branch except the anchor/0.30.1 fail

OS: Ubuntu 22.04
Rust version: 1.27.1 (54dd3d00f 2024-04-24)
Test environment: Clean Docker container

[dependencies]
anchor-lang = "=0.29.0"
anchor-spl = "=0.29.0"
whirlpool-cpi = { git = "https://github.com/orca-so/whirlpool-cpi", branch = "anchor/0.29.0" }

**Comment by yugure-orca** [comment]
@sirkuredda 
Could you provide the detail of build error.
And what version of Solana did you use ?
For example, anchor 0.29 should be used with Solana 1.17. (not 1.18 or 2.0)
